version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  fastapi:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - ./backend/app:/app
