version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile  # Ensure this matches the filename and path
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: messenger-app-mongodb
    ports:
      - "27017:27017"
